/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Ignore;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest
{
    @Ignore
    @Test public void testAppHasAGreeting()
    {
        App classUnderTest = new App();
    }
}
